{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "tssc-github-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: kubernetes.io/basic-auth
apiVersion: v1
metadata:
  name: gitops-auth-secret
  namespace: {{ $namespace }}-ci
data:
  password: {{ required "GitHub token is required in tssc-github-integration secret" $secretData.token }}
  username: {{ "oauth2" | b64enc }}
  {{- end }}
{{- end }}